apiVersion: apps/v1
kind: Deployment
metadata:
  name: little-help-book
  namespace: little-help-book
  labels:
    app: little-help-book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: little-help-book
  template:
    metadata:
      labels:
        app: little-help-book
    spec:
      containers:
      - name: little-help-book
        image: codegold79/little-help-book:0.1.0
        resources:
           limits:
              cpu: 0.25
              memory: 250Mi
           requests:
              cpu: 0.25
              memory: 250Mi
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1