apiVersion: v1
kind: Service
metadata:
  name: little-help-book

  namespace: little-help-book
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: stage-little-help-book-mapping
      host: mvpstudio.stage.apps.mvpstudio.org
      prefix: /api
      rewrite: /api
      service: mvpstudio-web-api.stage-mvpstudio-web
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: stage-little-help-book-web-www-mapping
      host: www.mvpstudio.stage.apps.mvpstudio.org
      prefix: /api
      rewrite: /api
      service: mvpstudio-web-api.stage-mvpstudio-web
      ---
      apiVersion: ambassador/v0
      kind: TLSContext
      name: stage-mvpstudio-web-api-tls
      hosts:
      - mvpstudio.stage.apps.mvpstudio.org
      - www.mvpstudio.stage.apps.mvpstudio.org
      secret: stage-apps-cert
spec:
  selector:
     app: little-help-book
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    