apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-little-help-book-deployment
  namespace: little-help-book-stage
  labels:
    app: little-help-book
spec:
  replicas: 1
  selector:
    matchLabels:
      app: little-help-book
  template:
    metadata:
      labels:
        app: little-help-book
    spec:
      containers:
        - name: web-server
          image: codegold79/little-help-book:0.1.1
          resources:
            limits:
              cpu: 0.25
              memory: 250Mi
            requests:
              cpu: 0.25
              memory: 250Mi
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
